---
- name: Create Alertmanager user
  user:
    name: "{{ alertmanager_user }}"
    shell: /sbin/nologin

- name: Download Alertmanager
  get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: "/tmp/alertmanager.tar.gz"

- name: Extract Alertmanager
  unarchive:
    src: "/tmp/alertmanager.tar.gz"
    dest: "{{ alertmanager_install_dir }}"
    remote_src: yes
    creates: "{{ alertmanager_install_dir }}/alertmanager"

- name: Create Alertmanager directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: 0755
  loop:
    - "{{ alertmanager_config_dir }}"
    - "/var/lib/alertmanager"

- name: Deploy Alertmanager configuration
  template:
    src: "alertmanager.yml.j2"
    dest: "{{ alertmanager_config_file }}"
    owner: "{{ alertmanager_user }}"
    group: "{{ alertmanager_group }}"
    mode: 0644

- name: Deploy Alertmanager systemd service
  copy:
    src: "alertmanager.service"
    dest: "/etc/systemd/system/alertmanager.service"
    mode: 0644

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start Alertmanager
  systemd:
    name: alertmanager
    enabled: yes
    state: started

